# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target "AlephAnimation" do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Hero'
  pod 'ViewAnimator'
  
  target "AlephAnimationTests" do
      pod 'Quick'
      pod 'Nimble'
  end
  
end



